### ISSUE TITLE
Running clustermaker on second network in a session using command tool comes back with error

### ISSUE THREAD

**Issue by risserlin** [RBVI/clusterMaker2#1]
Create 2 networks - network1 and network2
Run on first network
cluster mcl attribute="EM1_similarity_coeffecients" clusterAttribute="test1"
and clustermake works fine

Run on second network
cluster mcl attribute="EM2_similarity_coeffecients" clusterAttribute="test2"

crashes with below error:

Error in command tool output:
Error executing task: unrecognized (table entry): Node suid: 99 (table name): LOCAL_ATTRS

Stack:
AWT-EventQueue-0 ERROR [TaskMonitor.org.cytoscape.command.internal.CommandExecutorTask] - Error executing task: unrecognized (table entry): Node suid: 99  (table name): LOCAL_ATTRS
java.lang.IllegalArgumentException: unrecognized (table entry): Node suid: 99  (table name): LOCAL_ATTRS
    at org.cytoscape.model.internal.DefaultTablesNetwork.getRow(DefaultTablesNetwork.java:118)
    at org.cytoscape.model.internal.CySubNetworkImpl.getRow(CySubNetworkImpl.java:60)
    at edu.ucsf.rbvi.clusterMaker2.internal.utils.ModelUtils.createAndSet(ModelUtils.java:120)
    at edu.ucsf.rbvi.clusterMaker2.internal.utils.ModelUtils.createAndSetLocal(ModelUtils.java:110)
    at edu.ucsf.rbvi.clusterMaker2.internal.algorithms.networkClusterers.AbstractNetworkClusterer.createGroups(AbstractNetworkClusterer.java:79)
    at edu.ucsf.rbvi.clusterMaker2.internal.algorithms.networkClusterers.MCL.MCLCluster.run(MCLCluster.java:97)
    at org.cytoscape.command.internal.TFExecutor.execute(TFExecutor.java:90)
    at org.cytoscape.command.internal.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:180)
    at org.cytoscape.command.internal.CommandExecutorTask.run(CommandExecutorTask.java:54)
    at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:92)
    at org.cytoscape.commandDialog.internal.handlers.CommandHandler.handleCommand(CommandHandler.java:167)
    at org.cytoscape.commandDialog.internal.handlers.CommandHandler.handleCommand(CommandHandler.java:94)
    at org.cytoscape.commandDialog.internal.ui.CommandToolDialog.actionPerformed(CommandToolDialog.java:177)
    at javax.swing.JTextField.fireActionPerformed(JTextField.java:508)
    at javax.swing.JTextField.postActionEvent(JTextField.java:721)
    at javax.swing.JTextField$NotifyAction.actionPerformed(JTextField.java:836)
    at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1664)
    at javax.swing.JComponent.processKeyBinding(JComponent.java:2879)
    at javax.swing.JComponent.processKeyBindings(JComponent.java:2926)
    at javax.swing.JComponent.processKeyEvent(JComponent.java:2842)
    at java.awt.Component.processEvent(Component.java:6282)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1895)
    at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:762)
    at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1027)
    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:899)
    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:727)
    at java.awt.Component.dispatchEventImpl(Component.java:4731)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by cviner** [comment]
Do you think that you could release an update (i.e. via the Cytoscape App Store) for the application which includes this fix?

**Comment by RBVI** [comment]
OK, done.  Release 0.9.4 is up on the App store.  Note that since I've moved to Java 7, I updated the "minimum required version" to 3.2.  There is also a new results panel people might be interested in.

**Comment by cviner** [comment]
Thank you very much! 


-------- Original message --------
