### ISSUE TITLE
edgeCutoff slider doesn't work, also throws exception from command

### ISSUE THREAD

**Issue by mikekucera** [RBVI/clusterMaker2#10]
The edge cutoff slider on the mcl dialog doesn't move. Even manually setting a value in the text box doesn't work. Providing a value for the edgeCutoff parameter to the mcl command throws an exception.

```
java.lang.RuntimeException: Error processing arguments: Couldn't parse value from: 2.0 for setting: edgeCutOff
	at org.cytoscape.command.internal.tunables.CommandTunableInterceptorImpl.validateAndWriteBackTunables(CommandTunableInterceptorImpl.java:95)
	at org.cytoscape.command.internal.TFExecutor.execute(TFExecutor.java:82)
	at org.cytoscape.command.internal.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:175)
	at org.cytoscape.command.internal.CommandExecutorImpl.handleCommand(CommandExecutorImpl.java:216)
	at org.cytoscape.command.internal.CommandExecutorImpl.executeList(CommandExecutorImpl.java:154)
	at org.cytoscape.command.internal.CommandStringsExecutorTask.run(CommandStringsExecutorTask.java:50)
	at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:92)
	at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:108)
	at org.cytoscape.work.SynchronousTaskManager$pbryglu.execute(Unknown Source)
	at org.baderlab.autoannotate.internal.task.CreateAnnotationSetTask.runClusterMaker(CreateAnnotationSetTask.java:172)
	at org.baderlab.autoannotate.internal.task.CreateAnnotationSetTask.run(CreateAnnotationSetTask.java:77)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:342)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mikekucera** [comment]
From the log file...
```
Caused by: java.lang.IllegalArgumentException: Upper value is less than or equal to lower value
	at org.cytoscape.work.util.AbstractBounded.setBounds(AbstractBounded.java:180)
	at edu.ucsf.rbvi.clusterMaker2.internal.algorithms.edgeConverters.EdgeAttributeHandler.updateBounds(EdgeAttributeHandler.java:214)
	at edu.ucsf.rbvi.clusterMaker2.internal.algorithms.edgeConverters.EdgeAttributeHandler.getedgeCutOff(EdgeAttributeHandler.java:83)
```

**Comment by mikekucera** [comment]
Steps to reproduce the exception:
- open galFiltered
- select some nodes
- run the command
```cluster mcl attribute="--None--" selectedOnly=true ```
- run the command
```cluster mcl attribute="EdgeBetweenness" edgeCutOff="2.0" selectedOnly=true ```

**Comment by RBVI** [comment]
Mike, can you send me the file you are using?  I *believe* that it should throw an error, but the error message is incorrect.
