### ISSUE TITLE
Running clustermaker with only selected nodess selected doesn't work

### ISSUE THREAD

**Issue by risserlin** [RBVI/clusterMaker2#2]
Running clustermaker with only selected nodess selected doesn't work

Clustermaker2 version 0.94
Cytoscape 3.2.1
![screen shot 2015-04-16 at 10 54 12 am](https://cloud.githubusercontent.com/assets/3842763/7183681/f2c007b8-e426-11e4-81d2-d6737dc1055a.png)

Stack:
java.lang.ArrayIndexOutOfBoundsException: 0
    at edu.ucsf.rbvi.clusterMaker2.internal.algorithms.networkClusterers.MCL.RunMCL.create2DMatrix(RunMCL.java:347)
    at edu.ucsf.rbvi.clusterMaker2.internal.algorithms.networkClusterers.MCL.RunMCL.multiplyMatrix(RunMCL.java:343)
    at edu.ucsf.rbvi.clusterMaker2.internal.algorithms.networkClusterers.MCL.RunMCL.run(RunMCL.java:117)
    at edu.ucsf.rbvi.clusterMaker2.internal.algorithms.networkClusterers.MCL.MCLCluster.run(MCLCluster.java:86)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by risserlin** [comment]
this might have something to do with deleted edges.  I got the same error above when I re-ran clustering without using the selected nodes option.  

I saved the session and reopened it and both clustering and only selected nodes worked fine.

In the previous session I deleted a bunch of edges before trying to cluster when I got that error.
