### ISSUE TITLE
division by zero exception

### ISSUE THREAD

**Issue by mikekucera** [RBVI/clusterMaker2#9]
Task-Thread-1-Factory-0x4d570ccd ERROR [TaskMonitor.org.cytoscape.command.internal.CommandStringsExecutorTask] - Error executing task: / by zero
java.lang.ArithmeticException: / by zero
	at org.ojalgo.matrix.store.PrimitiveDenseStore.multiply(PrimitiveDenseStore.java:968)
	at edu.ucsf.rbvi.clusterMaker2.internal.algorithms.matrix.OjAlgoOps.multiplyMatrix(OjAlgoOps.java:335)
	at edu.ucsf.rbvi.clusterMaker2.internal.algorithms.networkClusterers.MCL.RunMCL.run(RunMCL.java:111)
	at edu.ucsf.rbvi.clusterMaker2.internal.algorithms.networkClusterers.MCL.MCLCluster.run(MCLCluster.java:91)
	at org.cytoscape.command.internal.TFExecutor.execute(TFExecutor.java:90)
	at org.cytoscape.command.internal.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:175)
	at org.cytoscape.command.internal.CommandExecutorImpl.handleCommand(CommandExecutorImpl.java:216)
	at org.cytoscape.command.internal.CommandExecutorImpl.executeList(CommandExecutorImpl.java:154)
	at org.cytoscape.command.internal.CommandStringsExecutorTask.run(CommandStringsExecutorTask.java:50)
	at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:92)
	at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:108)
	at org.cytoscape.work.SynchronousTaskManager$pbryglu.execute(Unknown Source)
	at org.baderlab.autoannotate.internal.task.CreateAnnotationSetTask.runClusterMaker(CreateAnnotationSetTask.java:172)
	at org.baderlab.autoannotate.internal.task.CreateAnnotationSetTask.run(CreateAnnotationSetTask.java:77)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:342)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mikekucera** [comment]
Steps to reproduce:
- open galFiltered
- run the following command
```
cluster mcl attribute="--None--" selectedOnly=true
```

**Comment by apete** [comment]
Most likely one of the matrices involved in the multiplication has 0 rows or columns.
